name: My Workflow

on:
  pull_request:
    branches: [main]
    types: [closed]


jobs:
  my-job:
    if: ${{ github.event.pull_request.merged == true }} 
    runs-on: ubuntu-latest
    steps:
      - name: My Step
        run: echo "My pipeline was triggered by a successful pull request merge."