name: deploy on merge to main

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    extends: ./build.yml#jobs.build
    steps:
      - name: save build folder as an artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy to production
        run: |
          echo "Deploying following to production..."
          du -lah build