name: deploy on merge to main

on:
  workflow_run:
    workflows: ["test"]
    branches: ["main"]
    tags: ["v*.*.*"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production..."