name: deploy on merge to main

on:
  push:
    tags: ["v*.*.*"]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production..."