name: test

on:
  push:

env:
  BRANCH_NAME: ${{ github.ref_name }}
  BRANCH_NAME_LAST: $(echo ${{ github.ref_name}} | awk -F'/' '{print $2}')

jobs:          
  call_bash:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [alice, bob]

    steps:
    - uses: actions/checkout@v3

    - name: run welcome bash script
      shell: bash
      run: |
        echo "Welcome to branch ${{ env.BRANCH_NAME_LAST }}"
        chmod +x ./scripts/welcome.sh
        ./scripts/welcome.sh ${{ matrix.name }}
        cat ./scripts/config.${{ matrix.name }}.json
