name: test

on:
  pull_request:

env:
  FROM_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  TO_BRANCH_NAME: ${{ github.event.pull_request.base.ref }}


jobs:          
  call_bash:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [ALICE, BOB]

    steps:
    - uses: actions/checkout@v3

    - name: run welcome bash script
      env:
        NAME_LOWERCASE: $( echo ${{ matrix.name }} | awk '{print tolower($0)}')
        FROM_BRANCH_LAST_LOWER: $( echo ${{ env.FROM_BRANCH_NAME }} | awk -F'/' '{print tolower($2)}')
        TO_BRANCH_LAST_UPPER: $( echo ${{ env.TO_BRANCH_NAME }} | awk -F'/' '{print toupper($2)}')
      shell: bash
      run: |
        echo "from: $FROM_BRANCH_NAME, to: $TO_BRANCH_NAME config: ${{ env.TO_BRANCH_LAST_UPPER }}"
        chmod +x ./scripts/welcome.sh
        ./scripts/welcome.sh ${{ matrix.name }}
        cat ./scripts/config.${{ env.NAME_LOWERCASE }}.json


    - name: get variable parametrically
      env:
        KEY: AZURE_${{ matrix.name }}_API_ID
      run: |
        echo ${{ matrix.name }} ID is ${{ vars[env.KEY] }}

