name: test

on:
  push:

jobs:          
  call_bash:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [alice, bob]

    steps:
    - uses: actions/checkout@v3

    - name: run welcome bash script
      shell: bash
      run: ./welcome.sh ${{ matrix.name }}
