name: test

on:
  push:

env:
  BRANCH_NAME: ${{ github.ref_name }}
  BRANCH_NAME_LAST_LOWER: $(echo ${{ github.ref_name }} | awk -F'/' '{print tolower($2)}')
  BRANCH_NAME_LAST_UPPER: $(echo ${{ github.ref_name }} | awk -F'/' '{print toupper($2)}')

jobs:          
  call_bash:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [ALICE, BOB]

    steps:
    - uses: actions/checkout@v3

    - name: run welcome bash script
      env:
        NAME_LOWERCASE: $( echo ${{ matrix.name }} | awk 'print tolower($0)')
      shell: bash
      run: |
        echo "Branch: ${{ env.BRANCH_NAME }}, ${{ env.BRANCH_NAME_LAST_LOWER }}, ${{ env.BRANCH_NAME_LAST_UPPER }}"
        chmod +x ./scripts/welcome.sh
        ./scripts/welcome.sh ${{ matrix.name }}
        cat ./scripts/config.${{ env.NAME_LOWERCASE }}.json


    - name: get variable parametrically
      env:
        KEY: AZURE_${{ matrix.name }}_API_ID
      run: |
        echo ${{ matrix.name}} ID is ${{ vars[env.KEY] }}

